import React from "react"

const Profile = () => {
	return (
		<div className={"main"}>
			<div className={"user-profile"}>
				<div className={"user__name"}>ShaggyBa</div>
				<div className={"profile__img"}>
					<img src="https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1213&q=80" alt="изображение профиля" />
				</div>
				<div className={"user__info"}>SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...
					SomeText...SomeText...SomeText...
					SomeText...SomeText...SomeText...SomeText...SomeText...SomeText
					...SomeText...SomeText...SomeText...SomeText...SomeText...SomeText...SomeText...SomeText...
					SomeText...SomeText...SomeText...SomeText...SomeText...SomeText...SomeText...</div>
			</div>
		</div>
	)
}

export default Profile